// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtb8BNjkeSC6DH2jRDwPF4FpJQ7kwxQcA',
    appId: '1:146494066932:web:15b25c65a1a155ae824ea1',
    messagingSenderId: '146494066932',
    projectId: 'instagram-clone-67521',
    authDomain: 'instagram-clone-67521.firebaseapp.com',
    storageBucket: 'instagram-clone-67521.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6C84sQx8F5STFGnUHSrPeOgZX6btg6MM',
    appId: '1:146494066932:android:6ff861213bb68d95824ea1',
    messagingSenderId: '146494066932',
    projectId: 'instagram-clone-67521',
    storageBucket: 'instagram-clone-67521.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyw3LbBEMFR5i1T658X36prUghMZNK254',
    appId: '1:146494066932:ios:1189f9ce5ba500ad824ea1',
    messagingSenderId: '146494066932',
    projectId: 'instagram-clone-67521',
    storageBucket: 'instagram-clone-67521.appspot.com',
    iosBundleId: 'com.example.projectapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyw3LbBEMFR5i1T658X36prUghMZNK254',
    appId: '1:146494066932:ios:1189f9ce5ba500ad824ea1',
    messagingSenderId: '146494066932',
    projectId: 'instagram-clone-67521',
    storageBucket: 'instagram-clone-67521.appspot.com',
    iosBundleId: 'com.example.projectapp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtb8BNjkeSC6DH2jRDwPF4FpJQ7kwxQcA',
    appId: '1:146494066932:web:df493d38089fb30b824ea1',
    messagingSenderId: '146494066932',
    projectId: 'instagram-clone-67521',
    authDomain: 'instagram-clone-67521.firebaseapp.com',
    storageBucket: 'instagram-clone-67521.appspot.com',
  );
}
